[package]
name = "reflex"
version = "0.1.0"
authors = ["Nasenheim"]

description = "A library to manage resource files."

edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
